import Head from 'next/head';
import { motion } from 'framer-motion';
import { useState, useEffect } from 'react';
import { BsFillMoonStarsFill, BsFillSunFill } from 'react-icons/bs';
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from 'react-icons/ai';
import { HiOutlineDocumentDownload, HiDocumentDownload } from 'react-icons/hi';
import Image from 'next/image';
import profile from '../public/profile.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';

export default function Home() {
  const [isOpen, setIsOpen] = useState(false);
  const [isOpenTwo, setIsOpenTwo] = useState(false);
  const [isOpen3, setIsOpen3] = useState(false);
  const [darkMode, setDarkMode] = useState(false);
  const [showResumeBtn, setShowResumeBtn] = useState(false);
  useEffect(() => {
    window.addEventListener('scroll', () => {
      if (window.scrollY > 50) {
        setShowResumeBtn(true);
      } else {
        setShowResumeBtn(false);
      }
    });
  }, []);

  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Matej portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-bold dark:text-white'>Matej</h1>
            <ul className='flex items-center'>
              <li onClick={() => setDarkMode(!darkMode)}>
                {darkMode ? (
                  <BsFillSunFill className='cursor-pointer text-2xl text-white' />
                ) : (
                  <BsFillMoonStarsFill className='cursor-pointer text-2xl' />
                )}
              </li>
              <li className=' bg-cyan-500  px-4 py-2 rounded-lg ml-8 hover:bg-teal-500 flex justify-center'>
                {darkMode ? (
                  <HiDocumentDownload className='h-6 w-4' />
                ) : (
                  <HiOutlineDocumentDownload className='h-6 w-4' />
                )}
                <a className='ml-1' href='../public/profile.png' download>
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className='text-center p-10 '>
            <h2 className='text-5xl py-2 text-cyan-500 font-medium md:text-6xl'>
              Matej Kovačević
            </h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>
              Developer and designer
            </h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-gray-500'>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero,
              autem?
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <a href='#'>
              <AiFillTwitterCircle className='hover:text-blue-500 dark:text-white dark:hover:text-blue-500' />
            </a>
            <a href='#'>
              <AiFillLinkedin className='hover:text-blue-800 dark:text-white dark:hover:text-blue-800' />
            </a>
            <a href='#'>
              <AiFillGithub className='hover:text-black dark:text-white dark:hover:text-black' />
            </a>
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden'>
            <Image src={profile} layout='fill' objectFit='cover' />
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-white'>Tools I use</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-500'>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione,
              quod?
            </p>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800'>
              <Image src={design} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-white'>
                Designing tools
              </h3>
              <p className='py-2 dark:text-gray-500'>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum,
                adipisci?
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1 dark:text-white'>Photoshop</p>
              <p className='text-gray-800 py-1 dark:text-white'>Figma</p>
            </div>

            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800'>
              <Image src={code} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-white'>
                Coding Languages
              </h3>
              <p className='py-2 dark:text-white'>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum,
                adipisci?
              </p>
              <h4 className='py-4 text-teal-600'>Coding languages I use</h4>
              <p className='text-gray-800 py-1 dark:text-white'>HTML</p>
              <p className='text-gray-800 py-1 dark:text-white'>React</p>
              <p className='text-gray-800 py-1 dark:text-white'>Next.js</p>
            </div>

            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800'>
              <Image src={consulting} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-white'>
                Styling tools
              </h3>
              <p className='py-2 dark:text-white'>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum,
                adipisci?
              </p>
              <h4 className='py-4 text-teal-600'>Styling tools I use</h4>
              <p className='text-gray-800 py-1 dark:text-white'>CSS</p>
              <p className='text-gray-800 py-1 dark:text-white'>Tailwind</p>
              <p className='text-gray-800 py-1 dark:text-white'>Bootstrap</p>
            </div>
          </div>
        </section>
        <section className='py-10'>
          <div>
            <h3 className='text-lg font-medium pt-8 pb-2 dark:text-white'>
              Portfolio
            </h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-500'>
              These are some of mine projects I worked on
            </p>
          </div>
          <div className='md:flex gap-10 justify-between rounded-xl'>
            <motion.div
              whileHover={{ scale: 1.05 }}
              transition={{ layout: { duration: 0.75, type: 'spring' } }}
              layout
              onClick={() => setIsOpen(!isOpen)}
              className='py-12 px-20 shadow-xl hover:cursor-pointer dark:bg-gray-800 dark:rounded-lg dark:mt-3'
            >
              <motion.h2
                layout=''
                className='text-xl border-b border-cyan-500 font-medium mb-4 dark:text-white'
              >
                Project One
              </motion.h2>
              {isOpen && (
                <motion.div>
                  <img
                    src='https://picsum.photos/200/300'
                    className='w-full h-80'
                    alt=''
                  />
                  <p className='pt-4 text-sm dark:text-white'>
                    Lorem ipsum dolor sit amet consectetur, adipisicing elit.
                    Voluptas, quaerat!
                  </p>
                  <p className='dark:text-white'>HTML</p>
                  <p className='dark:text-white'>CSS</p>
                  <p className='pb-4 dark:text-white'>Javascript</p>
                  <motion.a
                    whileTap={{ scale: 0.8 }}
                    href='#'
                    className='bg-cyan-500 text-white px-4 py-2 rounded-lg hover:bg-teal-500'
                  >
                    Code
                  </motion.a>
                  <a
                    href='#'
                    className='bg-cyan-500 text-white px-4 py-2 rounded-lg hover:bg-teal-500 ml-4'
                  >
                    Demo
                  </a>
                </motion.div>
              )}
            </motion.div>

            <motion.div
              whileHover={{ scale: 1.05 }}
              transition={{ layout: { duration: 0.75, type: 'spring' } }}
              layout
              onClick={() => setIsOpenTwo(!isOpenTwo)}
              className='py-12 px-20 shadow-xl hover:cursor-pointer dark:bg-gray-800 dark:rounded-lg dark:mt-3'
            >
              <motion.h2
                layout='position'
                className='text-xl font-medium mb-4 border-b border-cyan-500 dark:text-white'
              >
                Project Two
              </motion.h2>
              {isOpenTwo && (
                <motion.div>
                  <img
                    src='https://picsum.photos/200/300'
                    className='w-full h-80'
                    alt=''
                  />
                  <p className='pt-4 text-sm dark:text-white'>
                    Lorem ipsum dolor sit amet consectetur, adipisicing elit.
                    Voluptas, quaerat!
                  </p>
                  <p className='dark:text-white'>HTML</p>
                  <p className='dark:text-white'>CSS</p>
                  <p className='pb-4 dark:text-white'>Javascript</p>
                  <a
                    href='#'
                    className='bg-cyan-500 text-white px-4 py-2 rounded-lg hover:bg-teal-500'
                  >
                    Code
                  </a>
                  <a
                    href='#'
                    className='bg-cyan-500 text-white px-4 py-2 rounded-lg hover:bg-teal-500 ml-4'
                  >
                    Demo
                  </a>
                </motion.div>
              )}
            </motion.div>

            <motion.div
              whileHover={{ scale: 1.05 }}
              transition={{ layout: { duration: 0.75, type: 'spring' } }}
              layout
              onClick={() => setIsOpen3(!isOpen3)}
              className='py-12 px-20 shadow-xl  hover:cursor-pointer dark:bg-gray-800 dark:rounded-lg dark:mt-3'
            >
              <motion.h2
                layout='position'
                className='text-xl font-medium mb-4 border-b border-cyan-500 dark:text-white'
              >
                Project Three
              </motion.h2>
              {isOpen3 && (
                <motion.div>
                  <img
                    src='https://picsum.photos/200/300'
                    className='w-full h-80'
                    alt=''
                  />
                  <p className='pt-4 text-sm dark:text-white'>
                    Lorem ipsum dolor sit amet consectetur, adipisicing elit.
                    Voluptas, quaerat!
                  </p>
                  <p className='dark:text-white'>HTML</p>
                  <p className='dark:text-white'>CSS</p>
                  <p className='pb-4 dark:text-white'>Javascript</p>
                  <a
                    href='#'
                    className='bg-cyan-500 text-white px-4 py-2 rounded-lg hover:bg-teal-500'
                  >
                    Code
                  </a>
                  <a
                    href='#'
                    className='bg-cyan-500 text-white px-4 py-2 rounded-lg hover:bg-teal-500 ml-4'
                  >
                    Demo
                  </a>
                </motion.div>
              )}
            </motion.div>
          </div>
        </section>
        <section className=''>
          <div className='mb-10'>
            <h3 className='mb-3 text-lg font-medium pt-8 dark:text-white'>
              Lets talk
            </h3>
            <form className='md:w-1/3 md:mx-auto' action='get'>
              <div className='border-b border-cyan-500 mb-5'>
                <input
                  className='appearance-none bg-transparent border-none w-full text-gray-800 mr-3 py-1 px-2 leading-tight focus:outline-none'
                  placeholder='Email'
                  type='email'
                />
              </div>
              <div className='border-b border-cyan-500 mb-5'>
                <input
                  className='appearance-none bg-transparent border-none  text-gray-800 mr-3 py-1 px-2 leading-tight focus:outline-none'
                  placeholder='Name'
                  type='text'
                />
              </div>
              <div className='border-b border-cyan-500 mb-5'>
                <input
                  className='appearance-none bg-transparent border-none w-full text-gray-800 mr-3 py-1 px-2 leading-tight focus:outline-none'
                  placeholder='Message'
                  type='text-area'
                />
              </div>
              <div className=''>
                <button
                  className='bg-cyan-500 text-white px-4 py-2 rounded-lg mb-4 hover:bg-teal-500'
                  type='submit'
                >
                  Send it
                </button>
              </div>
            </form>
          </div>
        </section>
        <div>
          {' '}
          {showResumeBtn && (
            <motion.a
              initial={{ scale: 0 }}
              animate={{ rotate: 180, scale: 1 }}
              transition={{
                type: 'spring',
                stiffness: 260,
                damping: 20,
              }}
              href='../public/profile.png'
              download
            >
              {darkMode ? (
                <HiDocumentDownload className='fixed bottom-12 right-10 z-30 h-16 w-16 md:h-24 md:w-24 bg-cyan-500 rounded-full shadow-2xl p-2 hover:scale-110 cursor-pointer' />
              ) : (
                <HiOutlineDocumentDownload className='fixed bottom-12 right-10 z-30 h-16 w-16 md:h-24 md:w-24 bg-cyan-500 rounded-full shadow-2xl p-2 hover:scale-110 cursor-pointer' />
              )}
            </motion.a>
          )}
        </div>
      </main>
    </div>
  );
}
